Chromebook pages
Ultramarine-Linux/wiki pull request #18
Opened 2024-02-02 08:43 UTC by TheOwenSZ

2024-02-02 08:47 UTC, lleyton commented
The following is a demo for owen, pls ignore

2024-02-02 08:51 UTC, lleyton requested changes
You need more meows

2024-02-02 08:51 UTC, lleyton commented on src/consts.ts
> +      { text: "Getting Chromebook Edition", link: "en/chromebook/getting" },
This is bad because there should be more meows.
```suggestion
      { text: "Getting meowbook Edition", link: "en/chromebook/getting" },
```

2024-02-02 08:51 UTC, lleyton commented on src/content/docs/en/chromebook/chromebook.mdx
> +With the help from our friends over at the [Chrultrabook Project](https://docs.chrultrabook.com/), we built a no-hassle way to boot full Ultramarine Linux onto your Chromebook!
```suggestion
With the help from our meow friends over at the [Chrultrabook Project](https://docs.chrultrabook.com/), we built a no-hassle way to boot full Ultramarine Linux onto your Chromebook!
```

2024-02-03 07:44 UTC, meghan06 reviewed
Very slight nitpick. Looks good otherwise.

2024-02-03 07:44 UTC, meghan06 commented on src/content/docs/en/chromebook/getting.mdx
> +## Verifying the Safety of an Ultramarine image (Recommended)
image -> Image

2024-02-03 08:27 UTC, TheOwenSZ commented on src/content/docs/en/chromebook/getting.mdx
> +## Verifying the Safety of an Ultramarine image (Recommended)
Fixed, thanks!

2024-08-20 23:25 UTC, closed without merging